### ISSUE TITLE
Set-Location to Function directory

### ISSUE THREAD

**Issue by OgJAkFy8** [REN-Solutions/PowerTool#3]
In the PowerTool-Function.ps1 script on line 4 the command below: 
 `Set-Location -Path $PSScriptRoot`  

Changes the working location to the "Function" directory.  I think it should be removed, because if the working directory keeps changing throughout the modules it will eventually be set to the wrong location and more troubleshooting will have to happen to find out where it was changed last.  It should just be '.' sourced from the PowerTools Folder.

**Comment by OgJAkFy8** [comment]
Yeah.  So, I commented the line out and broke everything  ;-)  .  The removal is going to take a little more work than that.  More to follow.

**Comment by rynmdk** [comment]
Closing issue. Recreating this tool fully in C# therefore no longer will be an issue.

**Comment by OgJAkFy8** [comment]
Thanks for the update.
